# Generated by Django 5.2.12 on 2026-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_biometric_enabled_profile_email_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
