# Generated by Django 5.2.12 on 2026-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
