# Generated by Django 5.2.12 on 2026-05-11 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
            options={
                'unique_together': {('course', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(default='ONLINE', max_length=50)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('fee_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.feestructure')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
