# Generated by Django 5.2.12 on 2026-05-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_feestructure_studentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.CharField(blank=True, help_text='Optional parent grouping label, e.g. "IC" for all IC sub-departments', max_length=50, null=True),
        ),
    ]
