# Generated by Django 5.2.12 on 2026-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_subject_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
