# Generated by Django 5.2.12 on 2026-06-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='periods_per_week',
            field=models.IntegerField(default=3),
        ),
    ]
