# Generated by Django 5.2.12 on 2026-06-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_subject_periods_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.feestructure'),
        ),
    ]
