# Generated by Django 5.2.12 on 2026-06-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_studentpayment_fee_structure'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('course', 'year', 'batch')},
        ),
    ]
