# Generated by Django 5.2.13 on 2026-06-10 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_feestructure_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('10TH_MARKSHEET', '10th Marksheet'), ('12TH_MARKSHEET', '12th Marksheet'), ('DEGREE_CERTIFICATE', 'Degree Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('OTHER', 'Other Certificate/Marksheet')], default='OTHER', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='vault/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
